// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package integration

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

func Create(ctx context.Context, params *CreateParams) (*clerk.CommerceIntegration, error) {
	return getClient().Create(ctx, params)
}

func List(ctx context.Context, params *ListParams) (*clerk.CommerceIntegrationList, error) {
	return getClient().List(ctx, params)
}

func Get(ctx context.Context, id string) (*clerk.CommerceIntegration, error) {
	return getClient().Get(ctx, id)
}

func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.CommerceIntegration, error) {
	return getClient().Update(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
