// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package commerce

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// ListSubscriptionsByInstanceID returns a list of subscriptions for a given instance ID.
func ListSubscriptionsByInstanceID(ctx context.Context, params *ListSubscriptionsByInstanceIDParams) (*clerk.SubscriptionList, error) {
	return getClient().ListSubscriptionsByInstanceID(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
