// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package subscriptions

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

func Create(ctx context.Context, params *clerk.CreateSubscriptionParams) (*clerk.CommerceSubscription, error) {
	return getClient().Create(ctx, params)
}

func List(ctx context.Context, includes []string) (*clerk.ListCommerceSubscriptionsResponse, error) {
	return getClient().List(ctx, includes)
}

func ListInvoices(ctx context.Context, subscriptionID string) (*clerk.ListCommerceSubscriptionsResponse, error) {
	return getClient().ListInvoices(ctx, subscriptionID)
}

func ListByUserID(ctx context.Context, params *clerk.ListSubscriptionsByUserIDParams) (*clerk.ListCommerceSubscriptionsResponse, error) {
	return getClient().ListByUserID(ctx, params)
}

func Get(ctx context.Context, id string) (*clerk.CommerceSubscription, error) {
	return getClient().Get(ctx, id)
}

func Update(ctx context.Context, id string, params *clerk.UpdateSubscriptionParams) (*clerk.CommerceSubscription, error) {
	return getClient().Update(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
