// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package features

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

func Create(ctx context.Context, params *clerk.CreateFeatureParams) (*clerk.CommerceFeature, error) {
	return getClient().Create(ctx, params)
}

func CreatePlanFeature(ctx context.Context, params *clerk.CreatePlanFeatureParams) (*clerk.CommercePlanFeature, error) {
	return getClient().CreatePlanFeature(ctx, params)
}

func DeletePlanFeature(ctx context.Context, params *clerk.DeletePlanFeatureParams) error {
	return getClient().DeletePlanFeature(ctx, params)
}

func List(ctx context.Context, params *clerk.ListFeaturesByInstanceIDParams) (*clerk.CommerceFeatureList, error) {
	return getClient().List(ctx, params)
}

func ListByPlanID(ctx context.Context, params *clerk.ListFeaturesByPlanIDParams) (*clerk.CommerceFeatureList, error) {
	return getClient().ListByPlanID(ctx, params)
}

func Get(ctx context.Context, id string) (*clerk.CommerceFeature, error) {
	return getClient().Get(ctx, id)
}

func Delete(ctx context.Context, id string) error {
	return getClient().Delete(ctx, id)
}

func Update(ctx context.Context, id string, params *clerk.UpdateFeatureParams) (*clerk.CommerceFeature, error) {
	return getClient().Update(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
