// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package products

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

func CreateProduct(ctx context.Context, params *clerk.CreateProductParams) (*clerk.CommerceProduct, error) {
	return getClient().Create(ctx, params)
}

func ListProductsByInstanceID(ctx context.Context, params *clerk.ListProductsByInstanceIDParams) (*clerk.CommerceProductList, error) {
	return getClient().List(ctx, params)
}

func GetProductByID(ctx context.Context, id string) (*clerk.CommerceProduct, error) {
	return getClient().Get(ctx, id)
}

func UpdateProduct(ctx context.Context, id string, params *clerk.UpdateProductParams) (*clerk.CommerceProduct, error) {
	return getClient().Update(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
